### ISSUE TITLE
Official syntax and/or list of parameters

### ISSUE THREAD

**Issue by BenoitVDBr** [slundi/vivinq#1]
Hello,

This is not a real issue, but I was wondering if there is any 'official' documentation on the Vivino API to get to know the ins&outs of their API. Probably it isn't very recent, but it would help to know the limitations of their system and possibilities of the Vivino API.

Thanks!

Grtz,
Benoit.

**Comment by slundi** [comment]
Hi
There is no official API documentation, it was done through reverse engineering and existing similar projects (in other languages)
